/* Generated By:JavaCC: Do not edit this line. InterpretourConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpretourConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 36;
  /** RegularExpression Id. */
  int POSDIGIT = 37;
  /** RegularExpression Id. */
  int ZERO = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int IDENT = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"procedure\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"ref\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"var\"",
    "\"foreach\"",
    "\"=>\"",
    "\"in\"",
    "\"\\\\\"",
    "\"->\"",
    "\"<\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"..\"",
    "\"length\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 34>",
    "<token of kind 35>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
